### PR TITLE
Fix issue #38

### PR DESCRIPTION
**Pull request by laxa**
This small commit fixes issue #38 when installing current sources.

### CODE REVIEW

**Comment by c3c** [comment]
Thanks for the PR!
Before I accept, we should add a minimum version requirement for bloodhound in the setup.py, do you want to add that?
________________________________
From: Julien EGLOFF ***@***.***>
Sent: Monday, December 18, 2023 6:19:27 PM
To: c3c/ADExplorerSnapshot.py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [c3c/ADExplorerSnapshot.py] Fix issue #38 (PR #39)


This small commit fixes issue #38<https://github.com/c3c/ADExplorerSnapshot.py/issues/38> when installing current sources.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/c3c/ADExplorerSnapshot.py/pull/39

Commit Summary

  *   7313979<https://github.com/c3c/ADExplorerSnapshot.py/pull/39/commits/7313979619ea386d69f470eb8b1508ef42d611b7> Fix issue #38

File Changes

(1 file<https://github.com/c3c/ADExplorerSnapshot.py/pull/39/files>)

  *   M adexpsnapshot/__init__.py<https://github.com/c3c/ADExplorerSnapshot.py/pull/39/files#diff-921044e0048a35f62ca97595f22e7cbdd6c1ce05b481b618f024c4bdac1cf32f> (2)

Patch Links:

  *   https://github.com/c3c/ADExplorerSnapshot.py/pull/39.patch
  *   https://github.com/c3c/ADExplorerSnapshot.py/pull/39.diff

**Comment by laxa** [comment]
I updated the PR to require at least the 1.7.0 version where this change was introduced in bloodhound.py.

**Comment by dirkjanm** [comment]
note that this PR is no longer needed since I've removed the extra parameter which broke this in bloodhound.py 1.7.2

**Comment by laxa** [comment]
I updated the PR to only require version 1.7.2 then.

**Comment by c3c** [comment]
Gracias :)

**Pull request merged**
