### PR TITLE
Added certificate parsing of ADExplorer snapshots, based on Certipy.

### PR DESCRIPTION
**Pull request by PTVB**
Added certificate parsing from AD Snapshots, based on [Certipy](https://github.com/ly4k/Certipy).

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
any update on this to be merged?

**Comment by helloyw** [comment]
> Added certificate parsing from AD Snapshots, based on [Certipy](https://github.com/ly4k/Certipy).
I installed the latest ceripy4.4 and still encountered this issue
ModuleNotFoundError: No module named 'certipy.constants'
image

**Comment by c3c** [comment]
> > Added certificate parsing from AD Snapshots, based on [Certipy](https://github.com/ly4k/Certipy).
> > I installed the latest ceripy4.4 and still encountered this issue
> > ModuleNotFoundError: No module named 'certipy.constants'
> > image

should be fixed in new commit :)
thanks for making this, apologies for taking so long

**Comment by helloyw** [comment]
> > > 添加了基于[Certipy 的](https://github.com/ly4k/Certipy)AD 快照中的证书解析。
> > > 我安装了最新的ceripy4.4，仍然遇到这个问题
> > > ModuleNotFoundError: No module named 'certipy.constants'
> > > 图像
> 
> 应该在新的提交中修复 :) 感谢你做这个，抱歉花了这么长时间
I have a new issue. After resolving the issue of missing dependency packages, I successfully found 37 certificate templates using ADExplorerSnapshot.py. When I imported the generated JSON file into BloodHound 4.2.0-ly4k and used Find all Certificate Templates, I couldn't find any information.
image

**Comment by c3c** [comment]
Based on the output, you're working from a different branch than current main. I don't think that will resolve the problem though: current output format predates ly4k's version, that'll need to be implemented. I've created https://github.com/c3c/ADExplorerSnapshot.py/issues/17 to track this.

**Comment by helloyw** [comment]
> 根据输出，您正在与当前主分支不同的分支工作。我不认为这会解决问题：当前输出格式早于 ly4k 的版本，需要实施。我创建了#17来跟踪这个。

Great, looking forward to you solving this problem

**Comment by c3c** [comment]
Should be implemented with latest commits.
Make sure to re-run pip as dependency versions have changed.

**Comment by helloyw** [comment]
I tested the latest warehouse and found an error running, AttributeError: 'ADExplorerSnapshot' object has no attribute 'numCAS' Did you mean: 'numCAs'?， You need to globally replace numCAS with numCAs to successfully run，I hope you can modify this issue again
image

**Comment by c3c** [comment]
Ah forgot to stage that line for the main branch. https://github.com/c3c/ADExplorerSnapshot.py/commit/38e5100ee5925e1adfe63591f9df7fb97d35ca5e

**Comment by helloyw** [comment]
> 新刊参考

You did a great job

**Pull request merged**
